name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - main

permissions:
  id-token: write
  pull-requests: write
  contents: read
  actions: read

jobs:
  common-ci-checks:
    uses: ./.github/workflows/base.yml
    if: |
      !github.event.pull_request.draft || contains(github.event.pull_request.head.ref, 'ci-test')

  flexbench-checks:
    needs: common-ci-checks
    uses: ./.github/workflows/test.yml
