name: Test

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
      - releases/*

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          bash ./scripts/install_dependencies.sh

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build dependencies
        run: |
           bash ./scripts/install_server_dependencies.sh

      - name: Build vLLM CPU
        run: |
          VLLM_CPU_DISABLE_AVX512=false bash ./scripts/install_server_vllm.sh

      - name: Install project
        run: |
           bash ./scripts/install_flexbench.sh
           bash ./scripts/install_test_dependencies.sh


      - name: Run tests
        run: |
          bash ./scripts/run_tests.sh